# Winning Over Public Opinion By Measuring Minds Changed {#persuasion-metrics}
#### Keywords

persuasion, sentiment analysis, personality profiles, natural language processing, social media
<!-- BA: one thing I should think about is whether this course has been one long refutation of the very idea of persuasion, particularly those who are not fence-sitters or are somehow persuadable. What persuasion does seem to exist has been presented as manipulation or gaming the cognitive system of people. Also: very interesting concepts from Asynch 11... the notion that you extend an invitation, not an ask.-->
## Going beyond viewership
<!-- Fine, but read the headings by themselves. Do they also provide a synopsis? // BA: redo these at the end -->
Imagine you make a video to convince Americans that climate change is real and the video goes viral. Let's say 10 million people view it. Were you successful? It's impossible to answer that question without knowing how many of the viewers were climate skeptics before watching and accepted climate change after watching. This problem is writ large across organizations tasked with changing public opinion. Unlike online retailers with digital shopping carts, organizations that are selling ideas don't have a "buy" button to monitor. Consequently, these organizations -- including foundations, think tanks, political parties, and special interest groups -- are spending big money on content that they only vaguely know to be effective.
<!-- BA: should I simply whittle this down to one specific organization doing this, say Earthjustice, so I don't keep getting the frustrating comment that people aren't sure who would use this, despite iterating this list of types of organizations?-->
<!-- Pure numbers can be justified with some heavy assumptions. Indeed big numbers become even more important the weaker the effect. // BA: I think Brooks' basic take is that "weak indicator" data is good enough at scale, and "strong indicator" data of focus groups and polls are statistically valid to extend across big populations, so that this problem is already solved in two different ways. What this misses: The "weak indicator" data are very hard for non-technical orgs to know how to interpret, and the "strong indicator" data are too inexpensive and slow for daily decisionmaking by content-makers.-->
<!-- What kinds of buttons do they already have, or already use? // BA: there are various raw markers of engagement that are require more data to really understand what's meant by each user. But the raw markers are "likes" and other positive signs of engagement on social, site-specific reaction buttons ("Was this content helpful?"), Disqus comments, email to friend.  -->
<!-- BA: should I draw up a research question to end this section? -->
## Using sentiment analysis 
<!-- This section is about more than sentiment analysis. Indeed you'll want more than one method. // BA: change up header; other concepts are personality profiling, statistical experiments -->
Current solutions to the problem include focus groups and polling. Focus groups can measure the effectiveness of specific messaging phrases on a very small group in a highly artificial setting. Polling captures self-reported shifts in broad public opinion, but can't easily pinpoint that to any given content.
<!-- Polling could implement a pre-post within person design. // BA: Good point, so I think I need to amend this to highlight the slowness and extreme cost of this solution, as well as the bias of how people report to pollsters rather than observed response. -->
Cambridge Analytica, the firm hired by the Brexit and Trump campaigns, showed the potential of using big data to shift opinion through better audience targeting. Evidence suggests they used the data captured from Facebook likes to build personality [profiles of the entire U.S. population](/https://motherboard.vice.com/en_us/article/mg9vvn/how-our-likes-helped-trump-win), then delivered individuals specific online content to influence their opinions of Trump and Clinton. However, it's not clear they used anything innovative in determining which messages worked best -- instead, they could draw on the massive infrastructure of a national campaign with volunteers to check in on voters and get a rough sense of what worked. 

I see a tremendous opportunity to go further with data science to actually measure the persuasiveness of content. <!-- Subtle shift in unit of analysis. // BA: different than Measuring # of minds changed I guess. Okay. I prefer to talk about minds changed rather than scoring content. --> Populations can be split into opinion groups using [sentiment analysis](/https://en.wikipedia.org/wiki/Sentiment_analysis) of their social media posts on the topic. A certain group can be pushed persuasive content and monitored for changes in sentiment in their reaction and in any subsequent social media posts on the topic. In this way, opinion marketers can start to build conversion rate metrics on content, and piece together more sophisticated [remarketing campaigns](/http://rejoiner.com/resources/remarketing-vs-retargeting-whats-the-difference/).
<!-- How is social media policy changing to help or hinder such efforts? // BA: This was always tricky with Facebook. CambAn may have built personality profiles using online tests that users would voluntary open their account to scraping. Twitter has always seemed like anything goes as long as you don't try to scrape the entirety but play within their throttling. But I don't think he's asking about this level of detail, more the moral shift in silicon valley post election 2016. Also, the backlash from the Facebook emotions experiment. We'd have to avoid following pitfalls: targeting those holding hateful beliefs, offering false information to persuade, lack of transparency of who provides the messaging, and the lack of consent around the expriment. Probably should have a graf just on how to do this ethically, though there's some doubt in my mind if every one of those ethical boxes could be checked. -->
## A future with better arguments
<!-- better manipulation? consider unintended consequences // BA: he didn't seem to buy the better arguments frame. what is the difference between persuasion and manipulation to me? transparency/consent. the one being persuaded knows who is the persuader, knows that the persuader is trying to persuade. and accuracy. that the persuasion is being done with truthful information. -->
This initial solution to the problem of measuring what changes minds faces some serious limitations. Initial measurements may reveal that it is very rare for anyone's mind to change based on one piece of content, or that such shifts don't last very long without continuous messaging. And "change of mind" is rarely a binary event (a sudden flip from disagree to agree), but a slow shift along a continuum of opinion that may be harder to measure. But we won't know these shortfalls until taking this first step toward measuring persuasion. 
<!-- You're taking a tacitly cynical stance on democratic ethics. // BA: I guess he's saying that because I haven't addressed ethics to this point. I think this entire section will need to be an exploration of how one could do this ethically. -->
The solution would likely face ethical concerns around the tracking of individuals' opinions, though less so if the information is used purely to persuade rather than to exclude or penalize. 

Any metrics tools that get developed around persuasion would eventually spread to both sides of any given issue, so ultimately the data wouldn't result in any longlasting advantages to the first-movers. Instead, the metrics should help issue advocates argue better by clarifying misunderstandings and illuminating areas of real disagreement that need negotiation. The data could also save money for issue advocates who could determine that persuasion campaigns do not have the results to justify the expenditure. 
<!-- How to avoid a race to the bottom? -->
<!-- Brooks' final comments: I'm most fascinated by the moral ambivalence of this proposal. I probably enjoy it more for that reason, but I think clarifying your moral position will also help you develop more concrete tactics about what should be done. Attempting moral neutrality (albeit the dubious neutrality of an arms dealer) is one option, and currently the default. I would welcome some basic internal dialogue, for instance, about how ends justify means. // BA: Okay, so I will try to outline how to do this ethically.
Though I think you need to clarify your outcome of interest. "Minds changed" will quickly devolve into some measure of behavior, like engagement, and you need to decide whether you will hold the line against certain kinds of reductionism. System 1 will ride roughshod, after all! You will need to do some soul-searching about which particular commitment you want to make, because there are certain contradictions below. 
On the metrics side, there is an NLP angle, a social network angle, and a psychological angle. You have the third one covered here.
I know you're no stranger to headlines/headings, but consider whether reading your TOC alone actually delivers some microcosm of your proposal. // BA: I fixed the keywords, will fix the subheads
Given more space, you should attempt to demonstrate rather than assert these methodological arguments. Chasing numbers may make sense, but here you discount it almost entirely. You do not deny that there is a real conversion rate, indeed your proposal is all about measuring it. If you assume a range of conversion rates, how then does an interpretation of viral numbers change? // BA: Because I've seen how you get big numbers by pandering to pre-existing beliefs. Conversion rate is probably inversely related to traffic.
Don't overestimate the meaningfulness of sales for a corporation, or underestimate the meaning of existing metrics used by advocacy orgs Polling is probably the best method. It's also the most costly. In general though, think about how interview methods differ from observational methods. The main reason is people always know they are being interviewed (whether over the phone or by an online poll--also called an interview among methodologists). // BA: Okay work in this.
It does seem natural that some better form of instrumentation could ride on the coattails of these nuanced messaging tactics. But notice that they use a measurement of "natural" behavior (likes) to gather information. It is unclear then how they chose what content to push to any clusters they gleaned from like behavior. Perhaps it was the messages themselves that were or were not being liked? // BA: No, it was all manner of random things. See article. I think I need to distinguish in the writeup that you'd use likes and sentiment analysis to determine beliefs on climate change. But you might divide up that group into personality profiles (and your basic socioeconomic info) to target with different content, since different personality types may find different messaging more persuasive. I also could simply lose the whole Cambridge Analytica stuff and more simply envision a way to help advocacy orgs do framing tests online rather than in expensive focus groups.  
The earth may be shifting here, which is a big strategic question for the success of a concept like this. // BA: Right... the question around what's possible now that there's been a lot of pushback is definitely worth pondering. I need to enunciate an ethical version of this, which may mean dumping the personality profiling.
Here your ambivalence comes to the fore. Persuasion and argument may be very different things. One may appeal to reason, the other to everything but. // BA: ... I guess I feel like anything that isn't untruthful ultimately is fair game. What we know so far seems to indicate that relationships and stories matter, arguments from strangers don't. But I don't view storytelling from friends and family to be de facto manipulative like Brooks seems to. The prototype here is really same-sex marriage and the power of people coming out to friends and family. That's not manipulative.
I would highly recommend learning about Jürgen Habermas and his arguments about how democratic processes must be protected against manipulations. Your seem to believe that the only defense against manipulation is an arms race among the interests. You may be right, but it sounds treacherous, hence my fear of a race to the bottom if the data show that short-circuiting reason is always the best tactical approach. // BA: This comment and the next one indicate that Brooks actually would prefer that I undertake a very different approach to the problem of something like climate change denial. Rather than build better persuasion, he's arguing for the building of a better public square for debate. My first pushback to that is I have no idea who the client is for that kind of project. My second pushback is I simply don't believe a la Habermas that there existed some golden age of salons where private interest was sublimated in rational discourse to arrive at a public consensus. But I do take seriously the implicit challenge that if better persuasion metrics were developed, they would be deployed more forcefully by the sides with more money and power -- and that's not nonprofit advocacy, but major corporations. Unlike Habermas, who viewed mass media as turning citizens into spectators, I've seen how media gives people talking points for their beliefs, and these become starting points not endpoints. This project helps develop better starting points. That's I think the best I can do to respond to this. 
Some Habermas thinking: "Hence, Habermas describes a transition from the liberal public sphere which originated in the Enlightenment and the American and French Revolution to a media-dominated public sphere in the current era of what he calls "welfare state capitalism and mass democracy." This historical transformation is grounded, as noted, in Horkheimer and Adorno's analysis of the culture industry, in which giant corporations have taken over the public sphere and transformed it from a sphere of rational debate into one of manipulative consumption and passivity. In this transformation, "public opinion" shifts from rational consensus emerging from debate, discussion, and reflection to the manufactured opinion of polls or media experts. Rational debate and consensus has thus been replaced by managed discussion and manipulation by the machinations of advertising and political consulting agencies: "Publicity loses its critical function in favor of a staged display; even arguments are transmuted into symbols to which again one can not respond by arguing but only by identifying with them" (1989a: 206)." https://pages.gseis.ucla.edu/faculty/kellner/papers/habermas.htm
You may want to locate a project that adopts a very different paradigm. One that asks how tech can support deliberative democracy, for instance. In any event you should try to unearth some of the big assumptions you are making. The best way to do this is a "pre-mortem": what if you could implement your strategy. What would the consequences, intended and unintended, be? // BA: See above. But if I took this seriously, lack of any realistic client by damned, what would it look like? Perhaps you could analyze and bundle the arguments with the most currency among each faction on any given question like climate change. You could then analyze who seems to have the most compelling answer from another faction to that argument -- measured by attracting most attention from original faction and perhaps most change in expressed beliefs as a result of that. So in other words, map out the debate space and the factions and measure which interactions make the most difference organically. Do no broadcast messaging in this case, no experimenting -- just observing the discourse and from there learn which frames to amplify to which audience... and keep monitoring as the discussion develops. I *could* see making a strong tool around this. 
Do a little more to clarify who your client is. "Advantage" is a stakeholder dependent concept, and adopting a consistent perspective will go a long way to clarify and concretize your proposal. I'd recommend also reaching out on Slack to folks working on the "fake news" problem. There's a lot of opportunity for collaboration around that now, and I think you could hitch your cart to that for some useful dialogue. // BA: Let's do outreach after the cleanup on this concept. I guess I view the "fake news" fighters to be largely doing something different -- they are working at cleaning up the information space of false and misleading information. I need to find a way to clearly get the reader out of the mindset of fake news and Trump since that's proving to be a distraction. I am thinking that the Cambridge Analytica reference probably should be dumped. I really am interested in content that changes minds, not in changing minds by cleaning up the information landscape - which is what everyone is chasing right now. I reject that changing minds with content cannot be done ethically, however. Otherwise, what else do we mean by education? Why do we revere writing or artwork that made us think differently? Are all of those things "manipulative"?
Or just decide to be the one who gets there first :)-->

<!-- BA: outline of alternate concept. Evaluate reddit, disqus, twitter, facebook under articles to watch argumentation. Classify where people stand on the issue (looking especially for fence-sitters, then watch as they are exposed to challenging comments. Look for how they react (liking, or positive sentiments in response). Then look to see if they adopt that framing language later. Look to see too if it matters who makes the argument -- if it's the article itself, is the byline famous? If it's a commenter, is it someone they've had long interactions with? Try to get demographics of a list of users from the platforms. -->


start with the ethics section





The shape of the solution has been heavily influenced by ethical constraints. 


Envisioning the outcomes of this 



This shape of this project has been heavily influenced by what methods 

1. experimental vs observational - draw on the facebook emotion study. 
2. rather than push a lot of test messaging on unwitting subjects, we instead listen to organic conversation on the Internet. This bottom-up rather than broadcast model seeks to amplify messages from the public square, rather than more top-down propaganda. might invite those who were convinced by an argument and now making it to write on a public platform to a wider audience. testimonials of sorts. 
3. limiting to rational arguments, with full knowledge that shaping of emotions ahead would yield better results. - draw on the climate change study finding state of anxiety increased change in belief.
4. personality profiling - if there's really a way to do this without deception, but not sure there is. 

An earlier iteration of this project envisioned 




